module.exports.joke = [
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why can’t you give Elsa a balloon? Because she’ll let it go!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "Why did the bicycle fall over? It was two-tired.",
  "How does a penguin build its house? Igloos it together.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "Why did the math book look so sad? It had too many problems.",
  "What did one ocean say to the other ocean? Nothing, they just waved.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "What do you call a fake noodle? An impasta.",
  "Why did the scarecrow become a motivational speaker? Because he was outstanding in his field!",
];
